# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField(verbose_name='主机ip')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('brand', models.CharField(max_length=50, verbose_name='序列号')),
                ('cpu', models.CharField(max_length=50, verbose_name='cpu')),
                ('memory', models.CharField(max_length=50, verbose_name='内存大小')),
                ('system_version', models.CharField(max_length=50, verbose_name='系统版本')),
                ('is_active', models.BooleanField(default=False, verbose_name='服务器状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('changeTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '主机管理',
                'verbose_name_plural': '主机管理',
            },
        ),
    ]
