# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='id',
        ),
        migrations.AlterField(
            model_name='host',
            name='hostid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
