# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0002_auto_20181114_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='hostid',
            new_name='id',
        ),
    ]
