# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0003_auto_20181114_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='brand',
            field=models.CharField(max_length=50, null=True, verbose_name='序列号'),
        ),
    ]
