# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0004_auto_20181114_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.CharField(max_length=50, null=True, verbose_name='cpu'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(max_length=50, null=True, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='host',
            name='system_version',
            field=models.CharField(max_length=50, null=True, verbose_name='系统版本'),
        ),
    ]
