# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0005_auto_20181114_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='createTime',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='changeTime',
            new_name='last_login',
        ),
    ]
